/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TransmisionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "transmision";
};

export type ProgramaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "programa";
};

export type ContextoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contexto";
};

export type InfoGeneral = {
  _id: string;
  _type: "infoGeneral";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descripcion?: BlockContent;
  contacto?: string;
  redesSociales?: Array<{
    nombre?: string;
    url?: string;
    _type: "redSocial";
    _key: string;
  }>;
  configuracionDeTransmision?: string;
  destacados?: ArrayOf<TransmisionReference | ProgramaReference | ContextoReference>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PersonaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "persona";
};

export type GrupoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "grupo";
};

export type Publicacion = {
  _id: string;
  _type: "publicacion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  fecha?: string;
  tipoDePublicacion?: string;
  descripcion?: BlockContent;
  recursos?: Array<{
    titulo?: string;
    url?: string;
    archivo?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    _key: string;
  }>;
  creditos?: Array<PersonaReference | GrupoReference | PersonaReference | GrupoReference | PersonaReference | GrupoReference | PersonaReference | GrupoReference | PersonaReference | GrupoReference | PersonaReference | GrupoReference | PersonaReference | GrupoReference>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TipoDeTransmisionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tipoDeTransmision";
};

export type EspacioReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "espacio";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Transmision = {
  _id: string;
  _type: "transmision";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  programa?: ProgramaReference;
  esEpisodio?: boolean;
  numeroDeEpisodio?: number;
  esParteDeUnaTemporada?: boolean;
  numeroDeTemporada?: number;
  titulo?: string;
  slug?: Slug;
  descripcionCorta?: string;
  descripcion?: BlockContent;
  link?: {
    titulo?: string;
    url?: string;
    texto?: string;
  };
  fecha?: string;
  fechaFinal?: string;
  enVivo?: boolean;
  tipoDeTransmision?: Array<{
    _key: string;
  } & TipoDeTransmisionReference>;
  contexto?: ContextoReference;
  locacionGeografica?: {
    ciudad?: string;
    provincia?: string;
    pais?: string;
  };
  espacio?: EspacioReference;
  audio?: {
    url?: string;
    archivo?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  imagen?: {
    url?: string;
    archivo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  coproduccion?: ArrayOf<PersonaReference | GrupoReference>;
  invitadxs?: ArrayOf<PersonaReference | GrupoReference>;
  conduccion?: ArrayOf<PersonaReference | GrupoReference>;
  artistas?: ArrayOf<PersonaReference | GrupoReference>;
  piezasIncluidasDe?: ArrayOf<PersonaReference | GrupoReference>;
  tags?: Array<{
    _key: string;
  } & TagReference>;
};

export type Espacio = {
  _id: string;
  _type: "espacio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombre?: string;
  slug?: Slug;
  descripcion?: BlockContent;
  locacionGeografica?: {
    ciudad?: string;
    provincia?: string;
    pais?: string;
  };
  gestion?: ArrayOf<PersonaReference | GrupoReference>;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tag?: string;
};

export type Programa = {
  _id: string;
  _type: "programa";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  contexto?: ContextoReference;
  fecha?: string;
  descripcion?: BlockContent;
  descripcionCorta?: string;
  imagen?: {
    url?: string;
    archivo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  coproduccion?: ArrayOf<PersonaReference | GrupoReference>;
  tags?: Array<{
    _key: string;
  } & TagReference>;
};

export type TipoDeContextoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tipoDeContexto";
};

export type Contexto = {
  _id: string;
  _type: "contexto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  fecha?: string;
  fechaFinal?: string;
  descripcion?: BlockContent;
  tiposDeContexto?: Array<{
    _key: string;
  } & TipoDeContextoReference>;
  imagen?: {
    url?: string;
    archivo?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  produccion?: ArrayOf<PersonaReference | GrupoReference>;
  tags?: Array<{
    _key: string;
  } & TagReference>;
};

export type TipoDeTransmision = {
  _id: string;
  _type: "tipoDeTransmision";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tipoDeTransmision?: string;
};

export type TipoDeContexto = {
  _id: string;
  _type: "tipoDeContexto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tipoDeContexto?: string;
};

export type Grupo = {
  _id: string;
  _type: "grupo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombre?: string;
  slug?: Slug;
  integrantes?: Array<{
    _key: string;
  } & PersonaReference>;
  links?: Array<{
    titulo?: string;
    url?: string;
    _type: "link";
    _key: string;
  }>;
  paises?: Array<string>;
};

export type Persona = {
  _id: string;
  _type: "persona";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombre?: string;
  slug?: Slug;
  links?: Array<{
    titulo?: string;
    url?: string;
    _type: "link";
    _key: string;
  }>;
  paises?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | TransmisionReference | ProgramaReference | ContextoReference | InfoGeneral | BlockContent | SanityImageCrop | SanityImageHotspot | SanityFileAssetReference | PersonaReference | GrupoReference | Publicacion | Slug | TipoDeTransmisionReference | EspacioReference | TagReference | Transmision | Espacio | Tag | Programa | TipoDeContextoReference | Contexto | TipoDeTransmision | TipoDeContexto | Grupo | Persona | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<T & {
  _key: string;
}>;

// Source: ../radiocaso/src/domains/publication/api.ts
// Variable: publicationsQuery
// Query: *[_type == "publicacion"] | order(fecha desc) {       _id,      "title": titulo,      slug,      "date": fecha,      "publicationType": tipoDePublicacion,      "description": descripcion,      "resources": recursos[]->{        _id,        "title": titulo,        url,        "file": archivo{          asset->{            url          }        },      },      "credits": creditos    }
export type PublicationsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  publicationType: string | null;
  description: BlockContent | null;
  resources: Array<null> | null;
  credits: ArrayOf<GrupoReference | PersonaReference> | null;
}>;

// Source: ../radiocaso/src/domains/site/api.ts
// Variable: siteSettingsQuery
// Query: *[_type == "infoGeneral"][0] {    "title": titulo,    "info": descripcion,    "contact": contacto,    "socials": redesSociales,    logo,    "streamUrl": configuracionDeTransmision,    "highlighted": destacados[]->{      _id,      _type,      "title": titulo,      slug,    },  }
export type SiteSettingsQueryResult = {
  title: string | null;
  info: BlockContent | null;
  contact: string | null;
  socials: Array<{
    nombre?: string;
    url?: string;
    _type: "redSocial";
    _key: string;
  }> | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  streamUrl: string | null;
  highlighted: Array<{
    _id: string;
    _type: "contexto";
    title: string | null;
    slug: Slug | null;
  } | {
    _id: string;
    _type: "programa";
    title: string | null;
    slug: Slug | null;
  } | {
    _id: string;
    _type: "transmision";
    title: string | null;
    slug: Slug | null;
  }> | null;
} | null;

// Source: ../radiocaso/src/domains/transmission/api.ts
// Variable: futureTransmissionsQuery
// Query: *[_type == "transmision"] | order(fecha asc)[0..3] {     _id,    "title": titulo,    "date": fecha,    slug,    "transmissionType": tipoDeTransmision[]->{      _id,      "label": tipoDeTransmision    },    "program": programa->{      _id,      "title": titulo},    "context": contexto->{      _id,      "title": titulo},    "shortDescription": descripcionCorta,  }
export type FutureTransmissionsQueryResult = Array<{
  _id: string;
  title: string | null;
  date: string | null;
  slug: Slug | null;
  transmissionType: Array<{
    _id: string;
    label: string | null;
  }> | null;
  program: {
    _id: string;
    title: string | null;
  } | null;
  context: {
    _id: string;
    title: string | null;
  } | null;
  shortDescription: string | null;
}>;

// Source: ../radiocaso/src/domains/transmission/api.ts
// Variable: pastTransmissionsQuery
// Query: *[_type == "transmision"] | order(fecha desc) {    _id,    "title": titulo,    "date": fecha,    "transmissionType": tipoDeTransmision[]->{      _id,      "label": tipoDeTransmision    },    "program": programa->{      _id,      "title": titulo},    "context": contexto->{      _id,      "title": titulo},    "shortDescription": descripcionCorta,  }
export type PastTransmissionsQueryResult = Array<{
  _id: string;
  title: string | null;
  date: string | null;
  transmissionType: Array<{
    _id: string;
    label: string | null;
  }> | null;
  program: {
    _id: string;
    title: string | null;
  } | null;
  context: {
    _id: string;
    title: string | null;
  } | null;
  shortDescription: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"publicacion\"] | order(fecha desc) { \n      _id,\n      \"title\": titulo,\n      slug,\n      \"date\": fecha,\n      \"publicationType\": tipoDePublicacion,\n      \"description\": descripcion,\n      \"resources\": recursos[]->{\n        _id,\n        \"title\": titulo,\n        url,\n        \"file\": archivo{\n          asset->{\n            url\n          }\n        },\n      },\n      \"credits\": creditos\n    }": PublicationsQueryResult;
    "*[_type == \"infoGeneral\"][0] {\n    \"title\": titulo,\n    \"info\": descripcion,\n    \"contact\": contacto,\n    \"socials\": redesSociales,\n    logo,\n    \"streamUrl\": configuracionDeTransmision,\n    \"highlighted\": destacados[]->{\n      _id,\n      _type,\n      \"title\": titulo,\n      slug,\n    },\n  }": SiteSettingsQueryResult;
    "*[_type == \"transmision\"] | order(fecha asc)[0..3] { \n    _id,\n    \"title\": titulo,\n    \"date\": fecha,\n    slug,\n    \"transmissionType\": tipoDeTransmision[]->{\n      _id,\n      \"label\": tipoDeTransmision\n    },\n    \"program\": programa->{\n      _id,\n      \"title\": titulo},\n    \"context\": contexto->{\n      _id,\n      \"title\": titulo},\n    \"shortDescription\": descripcionCorta,\n  }": FutureTransmissionsQueryResult;
    "*[_type == \"transmision\"] | order(fecha desc) {\n    _id,\n    \"title\": titulo,\n    \"date\": fecha,\n    \"transmissionType\": tipoDeTransmision[]->{\n      _id,\n      \"label\": tipoDeTransmision\n    },\n    \"program\": programa->{\n      _id,\n      \"title\": titulo},\n    \"context\": contexto->{\n      _id,\n      \"title\": titulo},\n    \"shortDescription\": descripcionCorta,\n  }": PastTransmissionsQueryResult;
  }
}

